---
- name: Load a vars file according to OS/distro type, or a default, if not found
  include_vars: "{{ item }}"
  with_first_found:
  - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  - "{{ ansible_distribution }}.yml"
  - "{{ ansible_os_family }}.yml"
  - "default.yml"
